Fix TextInput.java - Comment out removed SpriteBatch API
LibGDX API change: SpriteBatch.overrideVertexType was removed
in newer versions. This was a workaround for VAO crashes in
v1.13.1 that is no longer needed.

Fixes compilation error in TextInput.java:71